# permissions for end users to view webctls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webctl-viewer-role
rules:
- apiGroups:
  - cache.harbor.misteruly.cn
  resources:
  - webctls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.harbor.misteruly.cn
  resources:
  - webctls/status
  verbs:
  - get
